### ISSUE TITLE
A Rare UnknownHostException in Flink Kinesis Consumer

### ISSUE THREAD

**Issue by sepulrator** [awslabs/amazon-kinesis-connector-flink#27]
Hi,
We have a KDA application (FLINK 1.11) that reads data from kinesis and writes to another Kinesis stream.
We are getting `java.net.UnknownHostException: kinesis.eu-west-1.amazonaws.com` a few times per month while the kinesis consumer reading data from kinesis.  After the exception, the job restarts itself and the problem disappears.
Is this an issue? How can we troubleshoot this? I would be really appreciated it if you could help me solving this.

Flink Kinesis Connector Version:1.0.4

### **Kinesis Consumer Properties:**
`"flink.shard.getrecords.intervalmillis": "500"`

### Stacktrace:**
`2021-04-18 16:23:24
software.amazon.kinesis.shaded.com.amazonaws.SdkClientException: Unable to execute HTTP request: kinesis.eu-west-1.amazonaws.com
	at software.amazon.kinesis.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207)
	at software.amazon.kinesis.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153)
	at software.amazon.kinesis.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at software.amazon.kinesis.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at software.amazon.kinesis.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at software.amazon.kinesis.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at software.amazon.kinesis.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at software.amazon.kinesis.shaded.com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at software.amazon.kinesis.shaded.com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at software.amazon.kinesis.shaded.com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2839)
	at software.amazon.kinesis.shaded.com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2806)
	at software.amazon.kinesis.shaded.com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2795)
	at software.amazon.kinesis.shaded.com.amazonaws.services.kinesis.AmazonKinesisClient.executeGetRecords(AmazonKinesisClient.java:1295)
	at software.amazon.kinesis.shaded.com.amazonaws.services.kinesis.AmazonKinesisClient.getRecords(AmazonKinesisClient.java:1266)
	at software.amazon.kinesis.connectors.flink.proxy.KinesisProxy.getRecords(KinesisProxy.java:247)
	at software.amazon.kinesis.connectors.flink.internals.publisher.polling.PollingRecordPublisher.getRecords(PollingRecordPublisher.java:155)
	at software.amazon.kinesis.connectors.flink.internals.publisher.polling.PollingRecordPublisher.run(PollingRecordPublisher.java:112)
	at software.amazon.kinesis.connectors.flink.internals.publisher.polling.PollingRecordPublisher.run(PollingRecordPublisher.java:102)
	at software.amazon.kinesis.connectors.flink.internals.ShardConsumer.run(ShardConsumer.java:108)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: **java.net.UnknownHostException: kinesis.eu-west-1.amazonaws.com**
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
	at software.amazon.kinesis.shaded.com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at software.amazon.kinesis.shaded.com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at software.amazon.kinesis.shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at software.amazon.kinesis.shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at software.amazon.kinesis.shaded.com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at software.amazon.kinesis.shaded.com.amazonaws.http.conn.$Proxy43.connect(Unknown Source)
	at software.amazon.kinesis.shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at software.amazon.kinesis.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at software.amazon.kinesis.shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at software.amazon.kinesis.shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at software.amazon.kinesis.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at software.amazon.kinesis.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at software.amazon.kinesis.shaded.com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at software.amazon.kinesis.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1330)
	at software.amazon.kinesis.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	... 22 more`

### **Job logs:**

`"locationInformation": "software.amazon.kinesis.shaded.com.amazonaws.services.kinesis.producer.LogInputStreamReader$6.apply(LogInputStreamReader.java:79)",
    "logger": "software.amazon.kinesis.shaded.com.amazonaws.services.kinesis.producer.LogInputStreamReader",
    "message": "[2021-04-18 13:23:23.261578] [0x00006d8d][0x00007f2e26e0b700] [error] [AWS Log: ERROR](AWSClient)HTTP response code: -1\nException name: \nError message: Unable to connect to endpoint\n0 response headers:",
    "threadName": "kpl-daemon-0003",`
    `"locationInformation": "software.amazon.kinesis.shaded.com.amazonaws.services.kinesis.producer.LogInputStreamReader$6.apply(LogInputStreamReader.java:79)",
    "logger": "software.amazon.kinesis.shaded.com.amazonaws.services.kinesis.producer.LogInputStreamReader",
    "message": "[2021-04-18 13:23:23.261522] [0x00006d8d][0x00007f2e26e0b700] [error] [AWS Log: ERROR](CurlHttpClient)Curl returned error code 6 - Couldn't resolve host name",
    "threadName": "kpl-daemon-0003",`

**Comment by GS-KeithLee** [comment]
Hi,

This seems like an issue within the environment that your KDA app runs on as opposed to. Please can you contact AWS Customer Support with your application ARN, time of incidence etc. so that they can help you get more details?

Thank you.

**Comment by sepulrator** [comment]
@GS-KeithLee Thanks for the quick reply. I will let you know whenever I have an update.

**Comment by dannycranmer** [comment]
Resolving issue as it is stale, please re-open if required
