### ISSUE TITLE
Getting IOException/StacklessClosedChannelException when consuming data from Kinesis

### ISSUE THREAD

**Issue by leonxu8** [awslabs/amazon-kinesis-connector-flink#51]
I used flink-1.12.5 kinesis connector to consume data from kinesis. From time to time I am getting IOException or StacklessClosedChannelException, which will fail the flink operator and trigger the job to restart. I am wondering if there's a better way to handle the error without restarting the flink job. Restarting the job is time-consuming and will often slow down the data consumption.

```
org.apache.flink.streaming.connectors.kinesis.internals.publisher.fanout.FanOutShardSubscriber$RetryableFanOutSubscriberException: org.apache.flink.kinesis.shaded.io.netty.channel.StacklessClosedChannelException
	at org.apache.flink.streaming.connectors.kinesis.internals.publisher.fanout.FanOutShardSubscriber.handleError(FanOutShardSubscriber.java:296) ~[blob_p-6581ced9ade704dee24c2632e701b413d2e656ba-f7515b4b21d25cb44b07411a9ad294e8:?]
	at org.apache.flink.streaming.connectors.kinesis.internals.publisher.fanout.FanOutShardSubscriber.consumeAllRecordsFromKinesisShard(FanOutShardSubscriber.java:363) ~[blob_p-6581ced9ade704dee24c2632e701b413d2e656ba-f7515b4b21d25cb44b07411a9ad294e8:?]
```

**Comment by leonxu8** [comment]
@dannycranmer Not sure if this is still the right place to post the question. I also send it to the flink user email list.
